export const featuredBrands = [
  "K-Swiss",
  "Foot Locker",
  "Hennessy",
  "Golden Boy",
  "iHeartRadio",
  "NFL",
  "Barclays Center",
  "TEDx",
  "Karen Civil",
  "Hair & The Blog",
  "King Me",
  "Headlines by De'Franco",
] as const;

export const allBrands = [
  ...featuredBrands,
  "Golden Boy Boxing",
  "CBS",
  "The Good Guys",
  "Bwagz",
  "Walk With Wagner",
  "NFL Honors",
  "Christian Kirksey",
  "Bobby Wagner",
  "Shaunie O'Neal",
  "Foot Locker North Park",
  "Green Bay Packers",
  "Jacksonville Jaguars",
  "Young Sheldon",
  "Boss Babe",
  "Mister Green",
  "If & Co.",
  "Dallas NorthPark",
  "San Diego",
] as const;
