export type WeddingSeed = {
  slug: string;
  title: string;
  kind: string;
  location: string;
  /** Local public path or external URL — uploaded to Sanity as an image asset */
  cover: string;
  /** Local public paths or external URLs — uploaded to Sanity as image assets */
  gallery: string[];
  /** External video URL or local /public path — stored as-is */
  video?: string;
  /** External poster/thumbnail URL — stored as-is */
  poster?: string;
  /** Local /public path for the looping tile preview video — stored as-is */
  previewVideo?: string;
  sortOrder: number;
};

export const weddingSeedData: WeddingSeed[] = [
  // ─────────────────────────────────────────────────────────────────────────
  // 1. Teagan's Proposal
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: 'teagan-and-issy-proposal',
    title: "Teagan & Issy's Proposal",
    kind: 'Proposal',
    location: 'Houston, TX',
    cover: '/weddings/collections/teagan-proposal/cover.jpg',
    gallery: [
      '/weddings/collections/teagan-proposal/photos/frame-001.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-002.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-003.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-004.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-005.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-006.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-007.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-008.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-009.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-010.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-011.jpg',
      '/weddings/collections/teagan-proposal/photos/frame-012.jpg',
    ],
    video:
      'https://drive.google.com/file/d/1WRjokRlFwTrUDoCELeqqN57HrFS4TXe9/view',
    sortOrder: 0,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 2. Mookie's Wedding
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: 'mookie-wedding',
    title: "Mookie & Brianna's Wedding",
    kind: 'Wedding',
    location: 'Los Angeles, CA',
    cover: '/weddings/collections/mookie-wedding/cover.jpg',
    gallery: [
      '/weddings/collections/mookie-wedding/photos/001.jpg',
      '/weddings/collections/mookie-wedding/photos/002.jpg',
      '/weddings/collections/mookie-wedding/photos/003.jpg',
      '/weddings/collections/mookie-wedding/photos/004.jpg',
      '/weddings/collections/mookie-wedding/photos/005.jpg',
      '/weddings/collections/mookie-wedding/photos/006.jpg',
      '/weddings/collections/mookie-wedding/photos/007.jpg',
      '/weddings/collections/mookie-wedding/photos/008.jpg',
      '/weddings/collections/mookie-wedding/photos/009.jpg',
      '/weddings/collections/mookie-wedding/photos/010.jpg',
      '/weddings/collections/mookie-wedding/photos/011.jpg',
      '/weddings/collections/mookie-wedding/photos/012.jpg',
      '/weddings/collections/mookie-wedding/photos/013.jpg',
      '/weddings/collections/mookie-wedding/photos/014.jpg',
      '/weddings/collections/mookie-wedding/photos/015.jpg',
      '/weddings/collections/mookie-wedding/photos/016.jpg',
      '/weddings/collections/mookie-wedding/photos/017.jpg',
      '/weddings/collections/mookie-wedding/photos/018.jpg',
      '/weddings/collections/mookie-wedding/photos/019.jpg',
      '/weddings/collections/mookie-wedding/photos/020.jpg',
      '/weddings/collections/mookie-wedding/photos/021.jpg',
      '/weddings/collections/mookie-wedding/photos/022.jpg',
      '/weddings/collections/mookie-wedding/photos/023.jpg',
      '/weddings/collections/mookie-wedding/photos/024.jpg',
      '/weddings/collections/mookie-wedding/photos/025.jpg',
      '/weddings/collections/mookie-wedding/photos/026.jpg',
      '/weddings/collections/mookie-wedding/photos/027.jpg',
      '/weddings/collections/mookie-wedding/photos/028.jpg',
      '/weddings/collections/mookie-wedding/photos/029.jpg',
      '/weddings/collections/mookie-wedding/photos/030.jpg',
      '/weddings/collections/mookie-wedding/photos/031.jpg',
      '/weddings/collections/mookie-wedding/photos/032.jpg',
      '/weddings/collections/mookie-wedding/photos/033.jpg',
      '/weddings/collections/mookie-wedding/photos/034.jpg',
      '/weddings/collections/mookie-wedding/photos/035.jpg',
      '/weddings/collections/mookie-wedding/photos/036.jpg',
      '/weddings/collections/mookie-wedding/photos/037.jpg',
      '/weddings/collections/mookie-wedding/photos/038.jpg',
      '/weddings/collections/mookie-wedding/photos/039.jpg',
      '/weddings/collections/mookie-wedding/photos/040.jpg',
      '/weddings/collections/mookie-wedding/photos/041.jpg',
      '/weddings/collections/mookie-wedding/photos/042.jpg',
      '/weddings/collections/mookie-wedding/photos/043.jpg',
      '/weddings/collections/mookie-wedding/photos/044.jpg',
      '/weddings/collections/mookie-wedding/photos/045.jpg',
      '/weddings/collections/mookie-wedding/photos/046.jpg',
      '/weddings/collections/mookie-wedding/photos/047.jpg',
      '/weddings/collections/mookie-wedding/photos/048.jpg',
      '/weddings/collections/mookie-wedding/photos/049.jpg',
      '/weddings/collections/mookie-wedding/photos/050.jpg',
      '/weddings/collections/mookie-wedding/photos/051.jpg',
      '/weddings/collections/mookie-wedding/photos/052.jpg',
      '/weddings/collections/mookie-wedding/photos/053.jpg',
      '/weddings/collections/mookie-wedding/photos/054.jpg',
      '/weddings/collections/mookie-wedding/photos/055.jpg',
      '/weddings/collections/mookie-wedding/photos/056.jpg',
      '/weddings/collections/mookie-wedding/photos/057.jpg',
      '/weddings/collections/mookie-wedding/photos/058.jpg',
      '/weddings/collections/mookie-wedding/photos/059.jpg',
      '/weddings/collections/mookie-wedding/photos/060.jpg',
      '/weddings/collections/mookie-wedding/photos/061.jpg',
      '/weddings/collections/mookie-wedding/photos/062.jpg',
      '/weddings/collections/mookie-wedding/photos/063.jpg',
      '/weddings/collections/mookie-wedding/photos/064.jpg',
      '/weddings/collections/mookie-wedding/photos/065.jpg',
      '/weddings/collections/mookie-wedding/photos/066.jpg',
      '/weddings/collections/mookie-wedding/photos/067.jpg',
      '/weddings/collections/mookie-wedding/photos/068.jpg',
      '/weddings/collections/mookie-wedding/photos/069.jpg',
      '/weddings/collections/mookie-wedding/photos/070.jpg',
      '/weddings/collections/mookie-wedding/photos/071.jpg',
      '/weddings/collections/mookie-wedding/photos/072.jpg',
      '/weddings/collections/mookie-wedding/photos/073.jpg',
      '/weddings/collections/mookie-wedding/photos/074.jpg',
      '/weddings/collections/mookie-wedding/photos/075.jpg',
      '/weddings/collections/mookie-wedding/photos/076.jpg',
      '/weddings/collections/mookie-wedding/photos/077.jpg',
      '/weddings/collections/mookie-wedding/photos/078.jpg',
      '/weddings/collections/mookie-wedding/photos/079.jpg',
      '/weddings/collections/mookie-wedding/photos/080.jpg',
      '/weddings/collections/mookie-wedding/photos/081.jpg',
    ],
    video: '/weddings/MrandMrsBettsWeddingTeaserwithNelly_1080.mp4',
    poster:
      'https://img.vidflow.co/studio/qkx4iiy6/deliverable/egwdmc2m/media/tpgnqjfs/i-WWJ2VRJ-X5.jpeg?width=1200&height=1200&optimize=image',
    sortOrder: 1,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 3. Christian's Wedding
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: 'christian-wedding',
    title: "Christian & Kendra's Wedding",
    kind: 'Wedding',
    location: 'Los Cabos, MX',
    cover: '/weddings/collections/christian-wedding/cover.jpg',
    gallery: [
      '/weddings/collections/christian-wedding/photos/001.jpg',
      '/weddings/collections/christian-wedding/photos/002.jpg',
      '/weddings/collections/christian-wedding/photos/003.jpg',
      '/weddings/collections/christian-wedding/photos/004.jpg',
      '/weddings/collections/christian-wedding/photos/005.jpg',
      '/weddings/collections/christian-wedding/photos/006.jpg',
      '/weddings/collections/christian-wedding/photos/007.jpg',
      '/weddings/collections/christian-wedding/photos/008.jpg',
      '/weddings/collections/christian-wedding/photos/009.jpg',
      '/weddings/collections/christian-wedding/photos/010.jpg',
      '/weddings/collections/christian-wedding/photos/011.jpg',
      '/weddings/collections/christian-wedding/photos/012.jpg',
      '/weddings/collections/christian-wedding/photos/013.jpg',
      '/weddings/collections/christian-wedding/photos/014.jpg',
      '/weddings/collections/christian-wedding/photos/015.jpg',
      '/weddings/collections/christian-wedding/photos/016.jpg',
      '/weddings/collections/christian-wedding/photos/017.jpg',
      '/weddings/collections/christian-wedding/photos/018.jpg',
      '/weddings/collections/christian-wedding/photos/019.jpg',
      '/weddings/collections/christian-wedding/photos/020.jpg',
      '/weddings/collections/christian-wedding/photos/021.jpg',
      '/weddings/collections/christian-wedding/photos/022.jpg',
      '/weddings/collections/christian-wedding/photos/023.jpg',
      '/weddings/collections/christian-wedding/photos/024.jpg',
      '/weddings/collections/christian-wedding/photos/025.jpg',
      '/weddings/collections/christian-wedding/photos/026.jpg',
      '/weddings/collections/christian-wedding/photos/027.jpg',
      '/weddings/collections/christian-wedding/photos/028.jpg',
      '/weddings/collections/christian-wedding/photos/029.jpg',
      '/weddings/collections/christian-wedding/photos/030.jpg',
      '/weddings/collections/christian-wedding/photos/031.jpg',
      '/weddings/collections/christian-wedding/photos/032.jpg',
      '/weddings/collections/christian-wedding/photos/033.jpg',
      '/weddings/collections/christian-wedding/photos/034.jpg',
      '/weddings/collections/christian-wedding/photos/035.jpg',
      '/weddings/collections/christian-wedding/photos/036.jpg',
      '/weddings/collections/christian-wedding/photos/037.jpg',
      '/weddings/collections/christian-wedding/photos/038.jpg',
      '/weddings/collections/christian-wedding/photos/039.jpg',
      '/weddings/collections/christian-wedding/photos/040.jpg',
      '/weddings/collections/christian-wedding/photos/041.jpg',
      '/weddings/collections/christian-wedding/photos/042.jpg',
      '/weddings/collections/christian-wedding/photos/043.jpg',
      '/weddings/collections/christian-wedding/photos/044.jpg',
      '/weddings/collections/christian-wedding/photos/045.jpg',
      '/weddings/collections/christian-wedding/photos/046.jpg',
      '/weddings/collections/christian-wedding/photos/047.jpg',
      '/weddings/collections/christian-wedding/photos/048.jpg',
      '/weddings/collections/christian-wedding/photos/049.jpg',
      '/weddings/collections/christian-wedding/photos/050.jpg',
      '/weddings/collections/christian-wedding/photos/051.jpg',
      '/weddings/collections/christian-wedding/photos/052.jpg',
      '/weddings/collections/christian-wedding/photos/053.jpg',
      '/weddings/collections/christian-wedding/photos/054.jpg',
      '/weddings/collections/christian-wedding/photos/055.jpg',
      '/weddings/collections/christian-wedding/photos/056.jpg',
      '/weddings/collections/christian-wedding/photos/057.jpg',
      '/weddings/collections/christian-wedding/photos/058.jpg',
      '/weddings/collections/christian-wedding/photos/059.jpg',
      '/weddings/collections/christian-wedding/photos/060.jpg',
      '/weddings/collections/christian-wedding/photos/061.jpg',
      '/weddings/collections/christian-wedding/photos/062.jpg',
      '/weddings/collections/christian-wedding/photos/063.jpg',
      '/weddings/collections/christian-wedding/photos/064.jpg',
      '/weddings/collections/christian-wedding/photos/065.jpg',
      '/weddings/collections/christian-wedding/photos/066.jpg',
      '/weddings/collections/christian-wedding/photos/067.jpg',
      '/weddings/collections/christian-wedding/photos/068.jpg',
      '/weddings/collections/christian-wedding/photos/069.jpg',
      '/weddings/collections/christian-wedding/photos/070.jpg',
      '/weddings/collections/christian-wedding/photos/071.jpg',
      '/weddings/collections/christian-wedding/photos/072.jpg',
      '/weddings/collections/christian-wedding/photos/073.jpg',
      '/weddings/collections/christian-wedding/photos/074.jpg',
      '/weddings/collections/christian-wedding/photos/075.jpg',
      '/weddings/collections/christian-wedding/photos/076.jpg',
      '/weddings/collections/christian-wedding/photos/077.jpg',
      '/weddings/collections/christian-wedding/photos/078.jpg',
      '/weddings/collections/christian-wedding/photos/079.jpg',
      '/weddings/collections/christian-wedding/photos/080.jpg',
      '/weddings/collections/christian-wedding/photos/081.jpg',
      '/weddings/collections/christian-wedding/photos/082.jpg',
      '/weddings/collections/christian-wedding/photos/083.jpg',
      '/weddings/collections/christian-wedding/photos/084.jpg',
      '/weddings/collections/christian-wedding/photos/085.jpg',
      '/weddings/collections/christian-wedding/photos/086.jpg',
      '/weddings/collections/christian-wedding/photos/087.jpg',
      '/weddings/collections/christian-wedding/photos/088.jpg',
      '/weddings/collections/christian-wedding/photos/089.jpg',
      '/weddings/collections/christian-wedding/photos/090.jpg',
      '/weddings/collections/christian-wedding/photos/091.jpg',
      '/weddings/collections/christian-wedding/photos/092.jpg',
      '/weddings/collections/christian-wedding/photos/093.jpg',
      '/weddings/collections/christian-wedding/photos/094.jpg',
      '/weddings/collections/christian-wedding/photos/095.jpg',
      '/weddings/collections/christian-wedding/photos/096.jpg',
      '/weddings/collections/christian-wedding/photos/097.jpg',
      '/weddings/collections/christian-wedding/photos/098.jpg',
      '/weddings/collections/christian-wedding/photos/099.jpg',
      '/weddings/collections/christian-wedding/photos/100.jpg',
      '/weddings/collections/christian-wedding/photos/101.jpg',
      '/weddings/collections/christian-wedding/photos/102.jpg',
      '/weddings/collections/christian-wedding/photos/103.jpg',
      '/weddings/collections/christian-wedding/photos/104.jpg',
      '/weddings/collections/christian-wedding/photos/105.jpg',
      '/weddings/collections/christian-wedding/photos/106.jpg',
      '/weddings/collections/christian-wedding/photos/107.jpg',
      '/weddings/collections/christian-wedding/photos/108.jpg',
      '/weddings/collections/christian-wedding/photos/109.jpg',
      '/weddings/collections/christian-wedding/photos/110.jpg',
      '/weddings/collections/christian-wedding/photos/111.jpg',
      '/weddings/collections/christian-wedding/photos/112.jpg',
      '/weddings/collections/christian-wedding/photos/113.jpg',
      '/weddings/collections/christian-wedding/photos/114.jpg',
      '/weddings/collections/christian-wedding/photos/115.jpg',
      '/weddings/collections/christian-wedding/photos/116.jpg',
      '/weddings/collections/christian-wedding/photos/117.jpg',
      '/weddings/collections/christian-wedding/photos/118.jpg',
      '/weddings/collections/christian-wedding/photos/119.jpg',
      '/weddings/collections/christian-wedding/photos/120.jpg',
      '/weddings/collections/christian-wedding/photos/121.jpg',
      '/weddings/collections/christian-wedding/photos/122.jpg',
      '/weddings/collections/christian-wedding/photos/123.jpg',
      '/weddings/collections/christian-wedding/photos/124.jpg',
      '/weddings/collections/christian-wedding/photos/125.jpg',
      '/weddings/collections/christian-wedding/photos/126.jpg',
      '/weddings/collections/christian-wedding/photos/127.jpg',
      '/weddings/collections/christian-wedding/photos/128.jpg',
      '/weddings/collections/christian-wedding/photos/129.jpg',
      '/weddings/collections/christian-wedding/photos/130.jpg',
      '/weddings/collections/christian-wedding/photos/131.jpg',
      '/weddings/collections/christian-wedding/photos/132.jpg',
      '/weddings/collections/christian-wedding/photos/133.jpg',
      '/weddings/collections/christian-wedding/photos/134.jpg',
      '/weddings/collections/christian-wedding/photos/135.jpg',
      '/weddings/collections/christian-wedding/photos/136.jpg',
      '/weddings/collections/christian-wedding/photos/137.jpg',
      '/weddings/collections/christian-wedding/photos/138.jpg',
      '/weddings/collections/christian-wedding/photos/139.jpg',
      '/weddings/collections/christian-wedding/photos/140.jpg',
      '/weddings/collections/christian-wedding/photos/141.jpg',
      '/weddings/collections/christian-wedding/photos/142.jpg',
      '/weddings/collections/christian-wedding/photos/143.jpg',
      '/weddings/collections/christian-wedding/photos/144.jpg',
      '/weddings/collections/christian-wedding/photos/145.jpg',
      '/weddings/collections/christian-wedding/photos/146.jpg',
      '/weddings/collections/christian-wedding/photos/147.jpg',
      '/weddings/collections/christian-wedding/photos/148.jpg',
      '/weddings/collections/christian-wedding/photos/149.jpg',
      '/weddings/collections/christian-wedding/photos/150.jpg',
      '/weddings/collections/christian-wedding/photos/151.jpg',
      '/weddings/collections/christian-wedding/photos/152.jpg',
      '/weddings/collections/christian-wedding/photos/153.jpg',
      '/weddings/collections/christian-wedding/photos/154.jpg',
      '/weddings/collections/christian-wedding/photos/155.jpg',
      '/weddings/collections/christian-wedding/photos/156.jpg',
      '/weddings/collections/christian-wedding/photos/157.jpg',
      '/weddings/collections/christian-wedding/photos/158.jpg',
      '/weddings/collections/christian-wedding/photos/159.jpg',
      '/weddings/collections/christian-wedding/photos/160.jpg',
      '/weddings/collections/christian-wedding/photos/161.jpg',
      '/weddings/collections/christian-wedding/photos/162.jpg',
      '/weddings/collections/christian-wedding/photos/163.jpg',
      '/weddings/collections/christian-wedding/photos/164.jpg',
      '/weddings/collections/christian-wedding/photos/165.jpg',
      '/weddings/collections/christian-wedding/photos/166.jpg',
      '/weddings/collections/christian-wedding/photos/167.jpg',
      '/weddings/collections/christian-wedding/photos/168.jpg',
      '/weddings/collections/christian-wedding/photos/169.jpg',
      '/weddings/collections/christian-wedding/photos/170.jpg',
      '/weddings/collections/christian-wedding/photos/171.jpg',
      '/weddings/collections/christian-wedding/photos/172.jpg',
      '/weddings/collections/christian-wedding/photos/173.jpg',
      '/weddings/collections/christian-wedding/photos/174.jpg',
      '/weddings/collections/christian-wedding/photos/175.jpg',
      '/weddings/collections/christian-wedding/photos/176.jpg',
      '/weddings/collections/christian-wedding/photos/177.jpg',
      '/weddings/collections/christian-wedding/photos/178.jpg',
      '/weddings/collections/christian-wedding/photos/179.jpg',
      '/weddings/collections/christian-wedding/photos/180.jpg',
      '/weddings/collections/christian-wedding/photos/181.jpg',
      '/weddings/collections/christian-wedding/photos/182.jpg',
      '/weddings/collections/christian-wedding/photos/183.jpg',
      '/weddings/collections/christian-wedding/photos/184.jpg',
      '/weddings/collections/christian-wedding/photos/185.jpg',
      '/weddings/collections/christian-wedding/photos/186.jpg',
      '/weddings/collections/christian-wedding/photos/187.jpg',
      '/weddings/collections/christian-wedding/photos/188.jpg',
      '/weddings/collections/christian-wedding/photos/189.jpg',
      '/weddings/collections/christian-wedding/photos/190.jpg',
      '/weddings/collections/christian-wedding/photos/191.jpg',
      '/weddings/collections/christian-wedding/photos/192.jpg',
    ],
    video: 'https://galleries.vidflow.co/9youtphy',
    poster:
      'https://img.vidflow.co/studio/qkx4iiy6/deliverable/9youtphy/media/9tqec7v4/Screenshot2023-03-28at113815PM.png?width=1200&height=1200&optimize=image',
    previewVideo: '/weddings/KENDRAANDCHRISTIANWEDDINGSNEAKPEAKWIDE_comp.mp4',
    sortOrder: 2,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 4. Christian's Engagement Shoot
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: 'christian-engagement',
    title: "Christian & Kendra's Engagement Shoot",
    kind: 'Engagement Shoot',
    location: 'Miami, FL',
    cover: '/weddings/collections/christian-engagement/cover.jpg',
    gallery: [
      '/weddings/collections/christian-engagement/photos/001.jpg',
      '/weddings/collections/christian-engagement/photos/002.jpg',
      '/weddings/collections/christian-engagement/photos/003.jpg',
      '/weddings/collections/christian-engagement/photos/004.jpg',
      '/weddings/collections/christian-engagement/photos/005.jpg',
      '/weddings/collections/christian-engagement/photos/006.jpg',
      '/weddings/collections/christian-engagement/photos/007.jpg',
      '/weddings/collections/christian-engagement/photos/008.jpg',
      '/weddings/collections/christian-engagement/photos/009.jpg',
      '/weddings/collections/christian-engagement/photos/010.jpg',
      '/weddings/collections/christian-engagement/photos/011.jpg',
      '/weddings/collections/christian-engagement/photos/012.jpg',
      '/weddings/collections/christian-engagement/photos/013.jpg',
      '/weddings/collections/christian-engagement/photos/014.jpg',
      '/weddings/collections/christian-engagement/photos/015.jpg',
      '/weddings/collections/christian-engagement/photos/016.jpg',
      '/weddings/collections/christian-engagement/photos/017.jpg',
      '/weddings/collections/christian-engagement/photos/018.jpg',
      '/weddings/collections/christian-engagement/photos/019.jpg',
      '/weddings/collections/christian-engagement/photos/020.jpg',
      '/weddings/collections/christian-engagement/photos/021.jpg',
      '/weddings/collections/christian-engagement/photos/022.jpg',
      '/weddings/collections/christian-engagement/photos/023.jpg',
      '/weddings/collections/christian-engagement/photos/024.jpg',
      '/weddings/collections/christian-engagement/photos/025.jpg',
      '/weddings/collections/christian-engagement/photos/026.jpg',
      '/weddings/collections/christian-engagement/photos/027.jpg',
      '/weddings/collections/christian-engagement/photos/028.jpg',
      '/weddings/collections/christian-engagement/photos/029.jpg',
      '/weddings/collections/christian-engagement/photos/030.jpg',
      '/weddings/collections/christian-engagement/photos/031.jpg',
      '/weddings/collections/christian-engagement/photos/032.jpg',
      '/weddings/collections/christian-engagement/photos/033.jpg',
      '/weddings/collections/christian-engagement/photos/034.jpg',
      '/weddings/collections/christian-engagement/photos/035.jpg',
      '/weddings/collections/christian-engagement/photos/036.jpg',
      '/weddings/collections/christian-engagement/photos/037.jpg',
      '/weddings/collections/christian-engagement/photos/038.jpg',
      '/weddings/collections/christian-engagement/photos/039.jpg',
      '/weddings/collections/christian-engagement/photos/040.jpg',
      '/weddings/collections/christian-engagement/photos/041.jpg',
      '/weddings/collections/christian-engagement/photos/042.jpg',
      '/weddings/collections/christian-engagement/photos/043.jpg',
      '/weddings/collections/christian-engagement/photos/044.jpg',
      '/weddings/collections/christian-engagement/photos/045.jpg',
      '/weddings/collections/christian-engagement/photos/046.jpg',
      '/weddings/collections/christian-engagement/photos/047.jpg',
      '/weddings/collections/christian-engagement/photos/048.jpg',
      '/weddings/collections/christian-engagement/photos/049.jpg',
      '/weddings/collections/christian-engagement/photos/050.jpg',
      '/weddings/collections/christian-engagement/photos/051.jpg',
      '/weddings/collections/christian-engagement/photos/052.jpg',
      '/weddings/collections/christian-engagement/photos/053.jpg',
      '/weddings/collections/christian-engagement/photos/054.jpg',
      '/weddings/collections/christian-engagement/photos/055.jpg',
      '/weddings/collections/christian-engagement/photos/056.jpg',
      '/weddings/collections/christian-engagement/photos/057.jpg',
      '/weddings/collections/christian-engagement/photos/058.jpg',
      '/weddings/collections/christian-engagement/photos/059.jpg',
      '/weddings/collections/christian-engagement/photos/060.jpg',
      '/weddings/collections/christian-engagement/photos/061.jpg',
      '/weddings/collections/christian-engagement/photos/062.jpg',
      '/weddings/collections/christian-engagement/photos/063.jpg',
      '/weddings/collections/christian-engagement/photos/064.jpg',
    ],
    sortOrder: 3,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 5. Christian's Proposal
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: 'christian-proposal',
    title: "Christian & Kendra's Proposal",
    kind: 'Proposal',
    location: 'Houston, TX',
    cover: '/weddings/collections/christian-proposal/cover.jpg',
    gallery: [
      '/weddings/collections/christian-proposal/photos/frame-001.jpg',
      '/weddings/collections/christian-proposal/photos/frame-002.jpg',
      '/weddings/collections/christian-proposal/photos/frame-003.jpg',
      '/weddings/collections/christian-proposal/photos/frame-004.jpg',
      '/weddings/collections/christian-proposal/photos/frame-005.jpg',
      '/weddings/collections/christian-proposal/photos/frame-006.jpg',
      '/weddings/collections/christian-proposal/photos/frame-007.jpg',
      '/weddings/collections/christian-proposal/photos/frame-008.jpg',
      '/weddings/collections/christian-proposal/photos/frame-009.jpg',
      '/weddings/collections/christian-proposal/photos/frame-010.jpg',
      '/weddings/collections/christian-proposal/photos/frame-011.jpg',
      '/weddings/collections/christian-proposal/photos/frame-012.jpg',
    ],
    video:
      'https://drive.google.com/file/d/1Kb9utbofSb0yNodKJbMh2zt9ERLeXh89/view',
    sortOrder: 4,
  },

  // ─────────────────────────────────────────────────────────────────────────
  // 6. Mookie's Proposal
  // ─────────────────────────────────────────────────────────────────────────
  {
    slug: 'mookie-proposal',
    title: "Mookie & Brianna's Proposal",
    kind: 'Proposal',
    location: 'Nashville, TN',
    cover: '/weddings/collections/mookie-proposal/cover.jpg',
    gallery: [
      '/weddings/collections/mookie-proposal/photos/001.jpg',
      '/weddings/collections/mookie-proposal/photos/002.jpg',
      '/weddings/collections/mookie-proposal/photos/003.jpg',
      '/weddings/collections/mookie-proposal/photos/004.jpg',
      '/weddings/collections/mookie-proposal/photos/005.jpg',
      '/weddings/collections/mookie-proposal/photos/006.jpg',
      '/weddings/collections/mookie-proposal/photos/007.jpg',
      '/weddings/collections/mookie-proposal/photos/008.jpg',
      '/weddings/collections/mookie-proposal/photos/009.jpg',
      '/weddings/collections/mookie-proposal/photos/010.jpg',
      '/weddings/collections/mookie-proposal/photos/011.jpg',
      '/weddings/collections/mookie-proposal/photos/012.jpg',
      '/weddings/collections/mookie-proposal/photos/013.jpg',
      '/weddings/collections/mookie-proposal/photos/014.jpg',
      '/weddings/collections/mookie-proposal/photos/015.jpg',
      '/weddings/collections/mookie-proposal/photos/016.jpg',
      '/weddings/collections/mookie-proposal/photos/017.jpg',
      '/weddings/collections/mookie-proposal/photos/018.jpg',
      '/weddings/collections/mookie-proposal/photos/019.jpg',
      '/weddings/collections/mookie-proposal/photos/020.jpg',
      '/weddings/collections/mookie-proposal/photos/021.jpg',
      '/weddings/collections/mookie-proposal/photos/022.jpg',
      '/weddings/collections/mookie-proposal/photos/023.jpg',
      '/weddings/collections/mookie-proposal/photos/024.jpg',
      '/weddings/collections/mookie-proposal/photos/025.jpg',
      '/weddings/collections/mookie-proposal/photos/026.jpg',
      '/weddings/collections/mookie-proposal/photos/027.jpg',
      '/weddings/collections/mookie-proposal/photos/028.jpg',
      '/weddings/collections/mookie-proposal/photos/029.jpg',
      '/weddings/collections/mookie-proposal/photos/030.jpg',
      '/weddings/collections/mookie-proposal/photos/031.jpg',
      '/weddings/collections/mookie-proposal/photos/032.jpg',
      '/weddings/collections/mookie-proposal/photos/033.jpg',
      '/weddings/collections/mookie-proposal/photos/034.jpg',
      '/weddings/collections/mookie-proposal/photos/035.jpg',
      '/weddings/collections/mookie-proposal/photos/036.jpg',
      '/weddings/collections/mookie-proposal/photos/037.jpg',
      '/weddings/collections/mookie-proposal/photos/038.jpg',
      '/weddings/collections/mookie-proposal/photos/039.jpg',
      '/weddings/collections/mookie-proposal/photos/040.jpg',
      '/weddings/collections/mookie-proposal/photos/041.jpg',
      '/weddings/collections/mookie-proposal/photos/042.jpg',
      '/weddings/collections/mookie-proposal/photos/043.jpg',
      '/weddings/collections/mookie-proposal/photos/044.jpg',
      '/weddings/collections/mookie-proposal/photos/045.jpg',
      '/weddings/collections/mookie-proposal/photos/046.jpg',
      '/weddings/collections/mookie-proposal/photos/047.jpg',
      '/weddings/collections/mookie-proposal/photos/048.jpg',
      '/weddings/collections/mookie-proposal/photos/049.jpg',
      '/weddings/collections/mookie-proposal/photos/050.jpg',
      '/weddings/collections/mookie-proposal/photos/051.jpg',
      '/weddings/collections/mookie-proposal/photos/052.jpg',
      '/weddings/collections/mookie-proposal/photos/053.jpg',
      '/weddings/collections/mookie-proposal/photos/054.jpg',
      '/weddings/collections/mookie-proposal/photos/055.jpg',
      '/weddings/collections/mookie-proposal/photos/056.jpg',
      '/weddings/collections/mookie-proposal/photos/057.jpg',
      '/weddings/collections/mookie-proposal/photos/058.jpg',
      '/weddings/collections/mookie-proposal/photos/059.jpg',
      '/weddings/collections/mookie-proposal/photos/060.jpg',
      '/weddings/collections/mookie-proposal/photos/061.jpg',
      '/weddings/collections/mookie-proposal/photos/062.jpg',
      '/weddings/collections/mookie-proposal/photos/063.jpg',
      '/weddings/collections/mookie-proposal/photos/064.jpg',
      '/weddings/collections/mookie-proposal/photos/065.jpg',
      '/weddings/collections/mookie-proposal/photos/066.jpg',
      '/weddings/collections/mookie-proposal/photos/067.jpg',
      '/weddings/collections/mookie-proposal/photos/068.jpg',
      '/weddings/collections/mookie-proposal/photos/069.jpg',
      '/weddings/collections/mookie-proposal/photos/070.jpg',
      '/weddings/collections/mookie-proposal/photos/071.jpg',
      '/weddings/collections/mookie-proposal/photos/072.jpg',
      '/weddings/collections/mookie-proposal/photos/073.jpg',
      '/weddings/collections/mookie-proposal/photos/074.jpg',
      '/weddings/collections/mookie-proposal/photos/075.jpg',
      '/weddings/collections/mookie-proposal/photos/076.jpg',
      '/weddings/collections/mookie-proposal/photos/077.jpg',
      '/weddings/collections/mookie-proposal/photos/078.jpg',
      '/weddings/collections/mookie-proposal/photos/079.jpg',
      '/weddings/collections/mookie-proposal/photos/080.jpg',
      '/weddings/collections/mookie-proposal/photos/081.jpg',
      '/weddings/collections/mookie-proposal/photos/082.jpg',
      '/weddings/collections/mookie-proposal/photos/083.jpg',
      '/weddings/collections/mookie-proposal/photos/084.jpg',
      '/weddings/collections/mookie-proposal/photos/085.jpg',
      '/weddings/collections/mookie-proposal/photos/086.jpg',
      '/weddings/collections/mookie-proposal/photos/087.jpg',
      '/weddings/collections/mookie-proposal/photos/088.jpg',
      '/weddings/collections/mookie-proposal/photos/089.jpg',
      '/weddings/collections/mookie-proposal/photos/090.jpg',
      '/weddings/collections/mookie-proposal/photos/091.jpg',
      '/weddings/collections/mookie-proposal/photos/092.jpg',
      '/weddings/collections/mookie-proposal/photos/093.jpg',
      '/weddings/collections/mookie-proposal/photos/094.jpg',
      '/weddings/collections/mookie-proposal/photos/095.jpg',
      '/weddings/collections/mookie-proposal/photos/096.jpg',
    ],
    video:
      'https://drive.google.com/file/d/10I2Nk3UFhuhThiGkghhaZPQNqy_T1rMw/view',
    sortOrder: 5,
  },
];
